// Code generated by napcatgen from NapCat OpenAPI 4.18.6; DO NOT EDIT.
// 由 napcatgen 根据 NapCat OpenAPI 4.18.6 生成；请勿手动修改。

package api

// DotHandleQuickOperationResponse 处理快速操作 响应数据。
type DotHandleQuickOperationResponse struct {
}

// DotOcrImageResponse 图片 OCR 识别 (内部) 响应数据。
type DotOcrImageResponse struct {
}

// ArkShareGroupResponse 分享群 (Ark) 响应数据。
type ArkShareGroupResponse struct {
}

// ArkSharePeerResponse 分享用户 (Ark) 响应数据。
type ArkSharePeerResponse struct {
}

// UnderscoreDelGroupNoticeResponse 删除群公告 响应数据。
type UnderscoreDelGroupNoticeResponse struct {
}

// UnderscoreGetGroupNoticeResponse 获取群公告 响应数据。
type UnderscoreGetGroupNoticeResponse struct {
}

// UnderscoreGetModelShowResponse 获取机型显示 响应数据。
type UnderscoreGetModelShowResponse struct {
}

// UnderscoreMarkAllAsReadResponse 标记所有消息已读 响应数据。
type UnderscoreMarkAllAsReadResponse struct {
}

// UnderscoreSendGroupNoticeResponse 发送群公告 响应数据。
type UnderscoreSendGroupNoticeResponse struct {
}

// UnderscoreSetModelShowResponse 设置机型 响应数据。
type UnderscoreSetModelShowResponse struct {
}

// AddCustomFaceResponse 添加自定义表情 响应数据。
type AddCustomFaceResponse struct {
}

// BotExitResponse 退出登录 响应数据。
type BotExitResponse struct {
}

// CanSendImageResponse 是否可以发送图片 响应数据。
type CanSendImageResponse struct {
	// Yes 是否可以发送
	Yes bool `json:"yes"`
}

// CanSendRecordResponse 是否可以发送语音 响应数据。
type CanSendRecordResponse struct {
	// Yes 是否可以发送
	Yes bool `json:"yes"`
}

// CancelGroupAlbumMediaLikeResponse 取消点赞群相册媒体 响应数据。
type CancelGroupAlbumMediaLikeResponse struct {
}

// CancelGroupTodoResponse 取消群待办 响应数据。
type CancelGroupTodoResponse struct {
}

// CancelOnlineFileResponse 取消在线文件 响应数据。
type CancelOnlineFileResponse struct {
}

// CheckURLSafelyResponse 检查URL安全性 响应数据。
type CheckURLSafelyResponse struct {
	// Level 安全等级 (1: 安全, 2: 未知, 3: 危险)
	Level int64 `json:"level"`
}

// CleanCacheResponse 清理缓存 响应数据。
type CleanCacheResponse struct {
}

// CleanStreamTempFileResponse 清理流式传输临时文件 响应数据。
type CleanStreamTempFileResponse struct {
}

// ClickInlineKeyboardButtonResponse 点击内联键盘按钮 响应数据。
type ClickInlineKeyboardButtonResponse struct {
}

// CompleteGroupTodoResponse 完成群待办 响应数据。
type CompleteGroupTodoResponse struct {
}

// CreateCollectionResponse 创建收藏 响应数据。
type CreateCollectionResponse struct {
}

// CreateFlashTaskResponse 创建闪传任务 响应数据。
type CreateFlashTaskResponse struct {
}

// CreateGroupFileFolderResponse 创建群文件目录 响应数据。
type CreateGroupFileFolderResponse struct {
	// GroupItem 群项信息
	GroupItem map[string]any `json:"groupItem"`
	// Result 操作结果
	Result map[string]any `json:"result"`
}

// DelGroupAlbumMediaResponse 删除群相册媒体 响应数据。
type DelGroupAlbumMediaResponse struct {
}

// DeleteCustomFaceResponse 删除自定义表情 响应数据。
type DeleteCustomFaceResponse struct {
}

// DeleteEssenceMsgResponse 移出精华消息 响应数据。
type DeleteEssenceMsgResponse struct {
}

// DeleteFriendResponse 删除好友 响应数据。
type DeleteFriendResponse struct {
}

// DeleteGroupFileResponse 删除群文件 响应数据。
type DeleteGroupFileResponse struct {
}

// DeleteGroupFolderResponse 删除群文件目录 响应数据。
type DeleteGroupFolderResponse struct {
}

// DeleteMsgResponse 撤回消息 响应数据。
type DeleteMsgResponse struct {
}

// DoGroupAlbumCommentResponse 发表群相册评论 响应数据。
type DoGroupAlbumCommentResponse struct {
}

// DownloadFileResponse 下载文件 响应数据。
type DownloadFileResponse struct {
	// File 文件路径
	File string `json:"file"`
}

// DownloadFileImageStreamResponse 下载图片文件流 响应数据。
type DownloadFileImageStreamResponse struct {
}

// DownloadFileRecordStreamResponse 下载语音文件流 响应数据。
type DownloadFileRecordStreamResponse struct {
}

// DownloadFileStreamResponse 下载文件流 响应数据。
type DownloadFileStreamResponse struct {
}

// DownloadFilesetResponse 下载文件集 响应数据。
type DownloadFilesetResponse struct {
}

// FetchCustomFaceResponse 获取自定义表情 响应数据。
type FetchCustomFaceResponse struct {
}

// FetchCustomFaceDetailResponse 获取自定义表情详情 响应数据。
type FetchCustomFaceDetailResponse struct {
}

// FetchEmojiLikeResponse 获取表情点赞详情 响应数据。
type FetchEmojiLikeResponse struct {
	// Cookie 分页Cookie
	Cookie string `json:"cookie"`
	// EmojiLikesList 表情回应列表
	EmojiLikesList []map[string]any `json:"emojiLikesList"`
	// ErrMsg 错 误信息
	ErrMsg string `json:"errMsg"`
	// IsFirstPage 是否第一页
	IsFirstPage bool `json:"isFirstPage"`
	// IsLastPage 是否最后一页
	IsLastPage bool `json:"isLastPage"`
	// Result 结果状态码
	Result int64 `json:"result"`
}

// FetchPttTextResponse 获取语音转文字结果 响应数据。
type FetchPttTextResponse struct {
	// Text 得到的文本
	Text string `json:"text"`
}

// ForwardFriendSingleMsgResponse 转发单条消息 响应数据。
type ForwardFriendSingleMsgResponse struct {
}

// ForwardGroupSingleMsgResponse 转发单条消息 响应数据。
type ForwardGroupSingleMsgResponse struct {
}

// FriendPokeResponse 发送戳一戳 响应数据。
type FriendPokeResponse struct {
}

// GetAiCharactersResponse 获取AI角色列表 响应数据。
type GetAiCharactersResponse struct {
}

// GetAiRecordResponse 获取 AI 语音 响应数据。
type GetAiRecordResponse struct {
}

// GetClientkeyResponse 获取ClientKey 响应数据。
type GetClientkeyResponse struct {
	// Clientkey 客户端Key
	Clientkey string `json:"clientkey,omitempty"`
}

// GetCollectionListResponse 获取收藏列表 响应数据。
type GetCollectionListResponse struct {
}

// GetCookiesResponse 获取 Cookies 响应数据。
type GetCookiesResponse struct {
	// Bkn CSRF Token
	Bkn string `json:"bkn"`
	// Cookies Cookies
	Cookies string `json:"cookies"`
}

// GetCredentialsResponse 获取登录凭证 响应数据。
type GetCredentialsResponse struct {
	// Cookies Cookies
	Cookies string `json:"cookies"`
	// Token CSRF Token
	Token int64 `json:"token"`
}

// GetCsrfTokenResponse 获取 CSRF Token 响应数据。
type GetCsrfTokenResponse struct {
	// Token CSRF Token
	Token int64 `json:"token"`
}

// GetDoubtFriendsAddRequestResponse 获取可疑好友申请 响应数据。
type GetDoubtFriendsAddRequestResponse struct {
}

// GetEmojiLikesResponse 获取消息表情点赞列表 响应数据。
type GetEmojiLikesResponse struct {
	// EmojiLikeList 表情回应列表
	EmojiLikeList []map[string]any `json:"emoji_like_list"`
}

// GetEssenceMsgListResponse 获取群精华消息 响应数据。
type GetEssenceMsgListResponse struct {
}

// GetFileResponse 获取文件 响应数据。
type GetFileResponse struct {
	// Base64 Base64编码
	Base64 string `json:"base64,omitempty"`
	// File 本地路径
	File string `json:"file,omitempty"`
	// FileName 文件名
	FileName string `json:"file_name,omitempty"`
	// FileSize 文件大小
	FileSize string `json:"file_size,omitempty"`
	// URL 下载URL
	URL string `json:"url,omitempty"`
}

// GetFilesetIDResponse 获取文件集 ID 响应数据。
type GetFilesetIDResponse struct {
	// FilesetID 文件集 ID
	FilesetID string `json:"fileset_id"`
}

// GetFilesetInfoResponse 获取文件集信息 响应数据。
type GetFilesetInfoResponse struct {
}

// GetFlashFileListResponse 获取闪传文件列表 响应数据。
type GetFlashFileListResponse struct {
}

// GetFlashFileURLResponse 获取闪传文件链接 响应数据。
type GetFlashFileURLResponse struct {
}

// GetForwardMsgResponse 获取合并转发消息 响应数据。
type GetForwardMsgResponse struct {
	// Messages 消息列表
	Messages []any `json:"messages,omitempty"`
}

// GetFriendListResponse 获取好友列表 响应数据。
type GetFriendListResponse struct {
}

// GetFriendMsgHistoryResponse 获取好友历史消息 响应数据。
type GetFriendMsgHistoryResponse struct {
	// Messages 消息列表
	Messages []any `json:"messages"`
}

// GetFriendsWithCategoryResponse 获取带分组的好友列表 响应数据。
type GetFriendsWithCategoryResponse struct {
}

// GetGroupAlbumMediaListResponse 获取群相册媒体列表 响应数据。
type GetGroupAlbumMediaListResponse struct {
}

// GetGroupAtAllRemainResponse 获取群艾特全体剩余次数 响应数据。
type GetGroupAtAllRemainResponse struct {
	// CanAtAll 是否可以艾特全体
	CanAtAll bool `json:"can_at_all"`
	// RemainAtAllCountForGroup 群艾特全体剩余次数
	RemainAtAllCountForGroup int64 `json:"remain_at_all_count_for_group"`
	// RemainAtAllCountForUIN 个人艾特全体剩余次数
	RemainAtAllCountForUIN int64 `json:"remain_at_all_count_for_uin"`
}

// GetGroupDetailInfoResponse 获取群详细信息 响应数据。
type GetGroupDetailInfoResponse struct {
	// GroupAllShut 全员禁言状态
	GroupAllShut int64 `json:"group_all_shut"`
	// GroupID 群号
	GroupID int64 `json:"group_id"`
	// GroupName 群名称
	GroupName string `json:"group_name"`
	// GroupRemark 群备注
	GroupRemark string `json:"group_remark"`
	// MaxMemberCount 最大成员数量
	MaxMemberCount int64 `json:"max_member_count"`
	// MemberCount 成员数量
	MemberCount int64 `json:"member_count"`
}

// GetGroupFileSystemInfoResponse 获取群文件系统信息 响应数据。
type GetGroupFileSystemInfoResponse struct {
	// FileCount 文件总数
	FileCount int64 `json:"file_count"`
	// LimitCount 文件上限
	LimitCount int64 `json:"limit_count"`
	// TotalSpace 总空间
	TotalSpace int64 `json:"total_space"`
	// UsedSpace 已使用空间
	UsedSpace int64 `json:"used_space"`
}

// GetGroupFileURLResponse 获取群文件URL 响应数据。
type GetGroupFileURLResponse struct {
	// URL 文件下载链接
	URL string `json:"url,omitempty"`
}

// GetGroupFilesByFolderResponse 获取群文件夹文件列表 响应数据。
type GetGroupFilesByFolderResponse struct {
	// Files 文件列表
	Files []any `json:"files"`
	// Folders 文件夹列表
	Folders []any `json:"folders"`
}

// GetGroupHonorInfoResponse 获取群荣誉信息 响应数据。
type GetGroupHonorInfoResponse struct {
	// CurrentTalkative 当前龙王
	CurrentTalkative map[string]any `json:"current_talkative"`
	// EmotionList 快乐源泉列表
	EmotionList []any `json:"emotion_list"`
	// GroupID 群号
	GroupID int64 `json:"group_id"`
	// LegendList 群聊炽热列表
	LegendList []any `json:"legend_list"`
	// PerformerList 群聊之火列表
	PerformerList []any `json:"performer_list"`
	// StrongNewbieList 冒尖小春笋列表
	StrongNewbieList []any `json:"strong_newbie_list"`
	// TalkativeList 龙王列表
	TalkativeList []any `json:"talkative_list"`
}

// GetGroupIgnoreAddRequestResponse 获取群被忽略的加群请求 响应数据。
type GetGroupIgnoreAddRequestResponse struct {
}

// GetGroupIgnoredNotifiesResponse 获取群忽略通知 响应数据。
type GetGroupIgnoredNotifiesResponse struct {
	// InvitedRequest 邀请请求列表
	InvitedRequest []any `json:"InvitedRequest"`
	// InvitedRequests 邀请请求列表
	InvitedRequests []any `json:"invited_requests"`
	// JoinRequests 加入请求列表
	JoinRequests []any `json:"join_requests"`
}

// GetGroupInfoResponse 获取群信息 响应数据。
type GetGroupInfoResponse struct {
	// GroupAllShut 是否全员禁言
	GroupAllShut int64 `json:"group_all_shut"`
	// GroupID 群号
	GroupID int64 `json:"group_id"`
	// GroupName 群名称
	GroupName string `json:"group_name"`
	// GroupRemark 群备注
	GroupRemark string `json:"group_remark"`
	// MaxMemberCount 最大成员人数
	MaxMemberCount int64 `json:"max_member_count,omitempty"`
	// MemberCount 成员人数
	MemberCount int64 `json:"member_count,omitempty"`
}

// GetGroupInfoExResponse 获取群详细信息 (扩展) 响应数据。
type GetGroupInfoExResponse struct {
}

// GetGroupListResponse 获取群列表 响应数据。
type GetGroupListResponse struct {
}

// GetGroupMemberInfoResponse 获取群成员信息 响应数据。
type GetGroupMemberInfoResponse struct {
	// Age 年龄
	Age int64 `json:"age,omitempty"`
	// Area 地区
	Area string `json:"area,omitempty"`
	// Card 名片
	Card string `json:"card,omitempty"`
	// CardChangeable 是否允许修改名片
	CardChangeable bool `json:"card_changeable,omitempty"`
	// GroupID 群号
	GroupID int64 `json:"group_id"`
	// IsRobot 是否为机器人
	IsRobot bool `json:"is_robot,omitempty"`
	// JoinTime 入群时间戳
	JoinTime int64 `json:"join_time,omitempty"`
	// LastSentTime 最后发言时间戳
	LastSentTime int64 `json:"last_sent_time,omitempty"`
	// Level 等级
	Level string `json:"level,omitempty"`
	// Nickname 昵称
	Nickname string `json:"nickname"`
	// Qage Q龄
	Qage int64 `json:"qage,omitempty"`
	// QQLevel QQ等级
	QQLevel int64 `json:"qq_level,omitempty"`
	// Role 角色 (owner/admin/member)
	Role string `json:"role,omitempty"`
	// Sex 性别
	Sex string `json:"sex,omitempty"`
	// ShutUpTimestamp 禁言截止时间戳
	ShutUpTimestamp int64 `json:"shut_up_timestamp,omitempty"`
	// Title 头衔
	Title string `json:"title,omitempty"`
	// TitleExpireTime 头衔过期时间
	TitleExpireTime int64 `json:"title_expire_time,omitempty"`
	// Unfriendly 是否不良记录
	Unfriendly bool `json:"unfriendly,omitempty"`
	// UserID QQ号
	UserID int64 `json:"user_id"`
}

// GetGroupMemberListResponse 获取群成员列表 响应数据。
type GetGroupMemberListResponse struct {
}

// GetGroupMsgHistoryResponse 获取群历史消息 响应数据。
type GetGroupMsgHistoryResponse struct {
	// Messages 消息列表
	Messages []any `json:"messages"`
}

// GetGroupRootFilesResponse 获取群根目录文件列表 响应数据。
type GetGroupRootFilesResponse struct {
	// Files 文件列表
	Files []any `json:"files"`
	// Folders 文件夹列表
	Folders []any `json:"folders"`
}

// GetGroupShutListResponse 获取群禁言列表 响应数据。
type GetGroupShutListResponse struct {
}

// GetGroupSignedListResponse 获取群组今日打卡列表 响应数据。
type GetGroupSignedListResponse struct {
}

// GetGroupSystemMsgResponse 获取群系统消息 响应数据。
type GetGroupSystemMsgResponse struct {
	// InvitedRequest 进群邀请列表 (兼容)
	InvitedRequest []map[string]any `json:"InvitedRequest"`
	// InvitedRequests 进群邀请列表
	InvitedRequests []map[string]any `json:"invited_requests"`
	// JoinRequests 进群申请列表
	JoinRequests []map[string]any `json:"join_requests"`
}

// GetGuildListResponse 获取频道列表 响应数据。
type GetGuildListResponse struct {
}

// GetGuildServiceProfileResponse 获取频道个人信息 响应数据。
type GetGuildServiceProfileResponse struct {
}

// GetImageResponse 获取图片 响应数据。
type GetImageResponse struct {
	// Base64 Base64编码
	Base64 string `json:"base64,omitempty"`
	// File 本地路径
	File string `json:"file,omitempty"`
	// FileName 文件名
	FileName string `json:"file_name,omitempty"`
	// FileSize 文件大小
	FileSize string `json:"file_size,omitempty"`
	// URL 下载URL
	URL string `json:"url,omitempty"`
}

// GetLoginInfoResponse 获取登录号信息 响应数据。
type GetLoginInfoResponse struct {
	// Age 年龄
	Age int64 `json:"age,omitempty"`
	// BirthdayDay 出生日期
	BirthdayDay int64 `json:"birthday_day,omitempty"`
	// BirthdayMonth 出生月份
	BirthdayMonth int64 `json:"birthday_month,omitempty"`
	// BirthdayYear 出生年份
	BirthdayYear int64 `json:"birthday_year,omitempty"`
	// CategoryId 分组ID
	CategoryId int64 `json:"categoryId,omitempty"`
	// CategoryName 分组名称
	CategoryName string `json:"categoryName,omitempty"`
	// CategoryID 分组ID
	CategoryID int64 `json:"category_id,omitempty"`
	// Email 邮箱
	Email string `json:"email,omitempty"`
	// Level 等级
	Level int64 `json:"level,omitempty"`
	// LoginDays 登录天数
	LoginDays int64 `json:"login_days,omitempty"`
	// Nickname 昵称
	Nickname string `json:"nickname"`
	// PhoneNum 手机号
	PhoneNum string `json:"phone_num,omitempty"`
	// QID QID
	QID string `json:"qid,omitempty"`
	// Remark 备注
	Remark string `json:"remark,omitempty"`
	// Sex 性别
	Sex string `json:"sex,omitempty"`
	// UserID QQ号
	UserID int64 `json:"user_id"`
}

// GetMiniAppArkResponse 获取小程序 Ark 响应数据。
type GetMiniAppArkResponse struct {
	// Data Ark数据
	Data map[string]any `json:"data"`
}

// GetMsgResponse 获取消息 响应数据。
type GetMsgResponse struct {
	// EmojiLikesList 表情回应列表
	EmojiLikesList []any `json:"emoji_likes_list,omitempty"`
	// Font 字体
	Font int64 `json:"font"`
	// GroupID 群号
	GroupID any `json:"group_id,omitempty"`
	// Message 消息内容
	Message map[string]any `json:"message"`
	// MessageID 消息ID
	MessageID int64 `json:"message_id"`
	// MessageSeq 消息序号
	MessageSeq int64 `json:"message_seq"`
	// MessageType 消息类型
	MessageType string `json:"message_type"`
	// RawMessage 原始消息内容
	RawMessage string `json:"raw_message"`
	// RealID 真实ID
	RealID int64 `json:"real_id"`
	// Sender 发送者
	Sender map[string]any `json:"sender"`
	// Time 发送时间
	Time int64 `json:"time"`
	// UserID 发送者QQ号
	UserID any `json:"user_id"`
}

// GetOnlineClientsResponse 获取在线客户端 响应数据。
type GetOnlineClientsResponse struct {
}

// GetOnlineFileMsgResponse 获取在线文件消息 响应数据。
type GetOnlineFileMsgResponse struct {
}

// GetPrivateFileURLResponse 获取私聊文件URL 响应数据。
type GetPrivateFileURLResponse struct {
	// URL 文件下载链接
	URL string `json:"url,omitempty"`
}

// GetProfileLikeResponse 获取资料点赞 响应数据。
type GetProfileLikeResponse struct {
	FavoriteInfo map[string]any `json:"favoriteInfo"`
	// Time 时间
	Time string `json:"time"`
	// UID 用户UID
	UID      string         `json:"uid"`
	VoteInfo map[string]any `json:"voteInfo"`
}

// GetQunAlbumListResponse 获取群相册列表 响应数据。
type GetQunAlbumListResponse struct {
	// AlbumList 群相册列表
	AlbumList []any `json:"album_list"`
	// AttachInfo 分页附加信息，传入下一次请求以获取更多数据
	AttachInfo string `json:"attach_info"`
	// HasMore 是否有更多数据
	HasMore bool `json:"has_more"`
}

// GetRecentContactResponse 获取最近会话 响应数据。
type GetRecentContactResponse struct {
}

// GetRecordResponse 获取语音 响应数据。
type GetRecordResponse struct {
	// Base64 Base64编码
	Base64 string `json:"base64,omitempty"`
	// File 本地路径
	File string `json:"file,omitempty"`
	// FileName 文件名
	FileName string `json:"file_name,omitempty"`
	// FileSize 文件大小
	FileSize string `json:"file_size,omitempty"`
	// URL 下载URL
	URL string `json:"url,omitempty"`
}

// GetRkeyResponse 获取扩展 RKey 响应数据。
type GetRkeyResponse struct {
}

// GetRkeyServerResponse 获取 RKey 服务器 响应数据。
type GetRkeyServerResponse struct {
	// ExpiredTime 过期时间
	ExpiredTime int64 `json:"expired_time,omitempty"`
	// GroupRkey 群聊 RKey
	GroupRkey string `json:"group_rkey,omitempty"`
	// Name 名称
	Name string `json:"name"`
	// PrivateRkey 私聊 RKey
	PrivateRkey string `json:"private_rkey,omitempty"`
}

// GetRobotUINRangeResponse 获取机器人 UIN 范围 响应数据。
type GetRobotUINRangeResponse struct {
}

// GetShareLinkResponse 获取文件分享链接 响应数据。
type GetShareLinkResponse struct {
}

// GetStatusResponse 获取运行状态 响应数据。
type GetStatusResponse struct {
	// Good 状态是否良好
	Good bool `json:"good"`
	// Online 是否在线
	Online bool `json:"online"`
	// Stat 统计信息
	Stat map[string]any `json:"stat"`
}

// GetStrangerInfoResponse 获取陌生人信息 响应数据。
type GetStrangerInfoResponse struct {
	// Age 年龄
	Age int64 `json:"age"`
	// IsVip 是否VIP
	IsVip bool `json:"is_vip"`
	// IsYearsVip 是否年费VIP
	IsYearsVip bool `json:"is_years_vip"`
	// LoginDays 登录天数
	LoginDays int64 `json:"login_days"`
	// LongNick 个性签名
	LongNick string `json:"long_nick"`
	// Nickname 昵称
	Nickname string `json:"nickname"`
	// QID QID
	QID string `json:"qid"`
	// QqLevel QQ等级
	QqLevel int64 `json:"qqLevel"`
	// RegTime 注册时间
	RegTime int64 `json:"reg_time"`
	// Remark 备注
	Remark string `json:"remark"`
	// Sex 性别
	Sex string `json:"sex"`
	// Status 状态
	Status int64 `json:"status"`
	// UID UID
	UID string `json:"uid"`
	// UserID 用户QQ
	UserID int64 `json:"user_id"`
	// VipLevel VIP等级
	VipLevel int64 `json:"vip_level"`
}

// GetUnidirectionalFriendListResponse 获取单向好友列表 响应数据。
type GetUnidirectionalFriendListResponse struct {
}

// GetVersionInfoResponse 获取版本信息 响应数据。
type GetVersionInfoResponse struct {
	// AppName 应用名称
	AppName string `json:"app_name"`
	// AppVersion 应用版本
	AppVersion string `json:"app_version"`
	// ProtocolVersion 协议版本
	ProtocolVersion string `json:"protocol_version"`
}

// GroupPokeResponse 发送戳一戳 响应数据。
type GroupPokeResponse struct {
}

// MarkGroupMsgAsReadResponse 标记群聊已读 响应数据。
type MarkGroupMsgAsReadResponse struct {
}

// MarkMsgAsReadResponse 标记消息已读 (Go-CQHTTP) 响应数据。
type MarkMsgAsReadResponse struct {
}

// MarkPrivateMsgAsReadResponse 标记私聊已读 响应数据。
type MarkPrivateMsgAsReadResponse struct {
}

// MoveGroupFileResponse 移动群文件 响应数据。
type MoveGroupFileResponse struct {
	// Ok 是否成功
	Ok bool `json:"ok"`
}

// NcGetPacketStatusResponse 获取Packet状态 响应数据。
type NcGetPacketStatusResponse struct {
}

// NcGetRkeyResponse 获取 RKey 响应数据。
type NcGetRkeyResponse struct {
}

// NcGetUserStatusResponse 获取用户在线状态 响应数据。
type NcGetUserStatusResponse struct {
	// ExtStatus 扩展状态
	ExtStatus int64 `json:"ext_status"`
	// Status 在线状态
	Status int64 `json:"status"`
}

// OcrImageResponse 图片 OCR 识别 响应数据。
type OcrImageResponse struct {
}

// ReceiveOnlineFileResponse 接收在线文件 响应数据。
type ReceiveOnlineFileResponse struct {
}

// RefuseOnlineFileResponse 拒绝在线文件 响应数据。
type RefuseOnlineFileResponse struct {
}

// RenameGroupFileResponse 重命名群文件 响应数据。
type RenameGroupFileResponse struct {
	// Ok 是否成功
	Ok bool `json:"ok"`
}

// SendArkShareResponse 分享用户 (Ark) 响应数据。
type SendArkShareResponse struct {
}

// SendFlashMsgResponse 发送闪传消息 响应数据。
type SendFlashMsgResponse struct {
}

// SendForwardMsgResponse 发送合并转发消息 响应数据。
type SendForwardMsgResponse struct {
	// ForwardID 转发消息的 forward_id
	ForwardID string `json:"forward_id,omitempty"`
	// MessageID 消息ID
	MessageID int64 `json:"message_id"`
	// ResID 转发消息的 res_id
	ResID string `json:"res_id,omitempty"`
}

// SendGroupAiRecordResponse 发送群 AI 语音 响应数据。
type SendGroupAiRecordResponse struct {
	// MessageID 消息ID
	MessageID int64 `json:"message_id"`
}

// SendGroupArkShareResponse 分享群 (Ark) 响应数据。
type SendGroupArkShareResponse struct {
}

// SendGroupForwardMsgResponse 发送群合并转发消息 响应数据。
type SendGroupForwardMsgResponse struct {
	// ForwardID 转发消息的 forward_id
	ForwardID string `json:"forward_id,omitempty"`
	// MessageID 消息ID
	MessageID int64 `json:"message_id"`
	// ResID 转发消息的 res_id
	ResID string `json:"res_id,omitempty"`
}

// SendGroupMsgResponse 发送群消息 响应数据。
type SendGroupMsgResponse struct {
	// ForwardID 转发消息的 forward_id
	ForwardID string `json:"forward_id,omitempty"`
	// MessageID 消息ID
	MessageID int64 `json:"message_id"`
	// ResID 转发消息的 res_id
	ResID string `json:"res_id,omitempty"`
}

// SendGroupSignResponse 群打卡 响应数据。
type SendGroupSignResponse struct {
}

// SendLikeResponse 点赞 响应数据。
type SendLikeResponse struct {
}

// SendMsgResponse 发送消息 响应数据。
type SendMsgResponse struct {
	// ForwardID 转发消息的 forward_id
	ForwardID string `json:"forward_id,omitempty"`
	// MessageID 消息ID
	MessageID int64 `json:"message_id"`
	// ResID 转发消息的 res_id
	ResID string `json:"res_id,omitempty"`
}

// SendOnlineFileResponse 发送在线文件 响应数据。
type SendOnlineFileResponse struct {
}

// SendOnlineFolderResponse 发送在线文件夹 响应数据。
type SendOnlineFolderResponse struct {
}

// SendPacketResponse 发送原始数据包 响应数据。
type SendPacketResponse struct {
}

// SendPokeResponse 发送戳一戳 响应数据。
type SendPokeResponse struct {
}

// SendPrivateForwardMsgResponse 发送私聊合并转发消息 响应数据。
type SendPrivateForwardMsgResponse struct {
	// ForwardID 转发消息的 forward_id
	ForwardID string `json:"forward_id,omitempty"`
	// MessageID 消息ID
	MessageID int64 `json:"message_id"`
	// ResID 转发消息的 res_id
	ResID string `json:"res_id,omitempty"`
}

// SendPrivateMsgResponse 发送私聊消息 响应数据。
type SendPrivateMsgResponse struct {
	// ForwardID 转发消息的 forward_id
	ForwardID string `json:"forward_id,omitempty"`
	// MessageID 消息ID
	MessageID int64 `json:"message_id"`
	// ResID 转发消息的 res_id
	ResID string `json:"res_id,omitempty"`
}

// SetCustomFaceDescResponse 修改自定义表情描述 响应数据。
type SetCustomFaceDescResponse struct {
}

// SetDiyOnlineStatusResponse 设置自定义在线状态 响应数据。
type SetDiyOnlineStatusResponse struct {
}

// SetDoubtFriendsAddRequestResponse 处理可疑好友申请 响应数据。
type SetDoubtFriendsAddRequestResponse struct {
}

// SetEssenceMsgResponse 设置精华消息 响应数据。
type SetEssenceMsgResponse struct {
}

// SetFriendAddRequestResponse 处理加好友请求 响应数据。
type SetFriendAddRequestResponse struct {
}

// SetFriendRemarkResponse 设置好友备注 响应数据。
type SetFriendRemarkResponse struct {
}

// SetGroupAddOptionResponse 设置群加群选项 响应数据。
type SetGroupAddOptionResponse struct {
}

// SetGroupAddRequestResponse 处理加群请求 响应数据。
type SetGroupAddRequestResponse struct {
}

// SetGroupAdminResponse 设置群管理员 响应数据。
type SetGroupAdminResponse struct {
}

// SetGroupAlbumMediaLikeResponse 点赞群相册媒体 响应数据。
type SetGroupAlbumMediaLikeResponse struct {
}

// SetGroupBanResponse 群组禁言 响应数据。
type SetGroupBanResponse struct {
}

// SetGroupCardResponse 设置群名片 响应数据。
type SetGroupCardResponse struct {
}

// SetGroupKickResponse 群组踢人 响应数据。
type SetGroupKickResponse struct {
}

// SetGroupKickMembersResponse 批量踢出群成员 响应数据。
type SetGroupKickMembersResponse struct {
}

// SetGroupLeaveResponse 退出群组 响应数据。
type SetGroupLeaveResponse struct {
}

// SetGroupNameResponse 设置群名称 响应数据。
type SetGroupNameResponse struct {
}

// SetGroupPortraitResponse 设置群头像 响应数据。
type SetGroupPortraitResponse struct {
	ErrMsg string `json:"errMsg"`
	Result int64  `json:"result"`
}

// SetGroupRemarkResponse 设置群备注 响应数据。
type SetGroupRemarkResponse struct {
}

// SetGroupRobotAddOptionResponse 设置群机器人加群选项 响应数据。
type SetGroupRobotAddOptionResponse struct {
}

// SetGroupSearchResponse 设置群搜索选项 响应数据。
type SetGroupSearchResponse struct {
}

// SetGroupSignResponse 群打卡 响应数据。
type SetGroupSignResponse struct {
}

// SetGroupSpecialTitleResponse 设置专属头衔 响应数据。
type SetGroupSpecialTitleResponse struct {
}

// SetGroupTodoResponse 设置群待办 响应数据。
type SetGroupTodoResponse struct {
}

// SetGroupWholeBanResponse 全员禁言 响应数据。
type SetGroupWholeBanResponse struct {
}

// SetInputStatusResponse 设置输入状态 响应数据。
type SetInputStatusResponse struct {
}

// SetMsgEmojiLikeResponse 设置消息表情点赞 响应数据。
type SetMsgEmojiLikeResponse struct {
}

// SetOnlineStatusResponse 设置在线状态 响应数据。
type SetOnlineStatusResponse struct {
}

// SetQQAvatarResponse 设置QQ头像 响应数据。
type SetQQAvatarResponse struct {
}

// SetQQProfileResponse 设置QQ资料 响应数据。
type SetQQProfileResponse struct {
}

// SetRestartResponse 重启服务 响应数据。
type SetRestartResponse struct {
}

// SetSelfLongnickResponse 设置个性签名 响应数据。
type SetSelfLongnickResponse struct {
}

// TestDownloadStreamResponse 测试下载流 响应数据。
type TestDownloadStreamResponse struct {
}

// TransGroupFileResponse 传输群文件 响应数据。
type TransGroupFileResponse struct {
	// Ok 是否成功
	Ok bool `json:"ok"`
}

// TranslateEn2zhResponse 英文单词翻译 响应数据。
type TranslateEn2zhResponse struct {
	// Words 翻译结果列表
	Words []string `json:"words"`
}

// UploadFileStreamResponse 上传文件流 响应数据。
type UploadFileStreamResponse struct {
}

// UploadGroupFileResponse 上传群文件 响应数据。
type UploadGroupFileResponse struct {
	// FileID 文件 ID
	FileID any `json:"file_id"`
}

// UploadImageToQunAlbumResponse 上传图片到群相册 响应数据。
type UploadImageToQunAlbumResponse struct {
}

// UploadPrivateFileResponse 上传私聊文件 响应数据。
type UploadPrivateFileResponse struct {
	// FileID 文件 ID
	FileID any `json:"file_id"`
}
