// Code generated by napcatgen from NapCat OpenAPI 4.18.6; DO NOT EDIT.
// 由 napcatgen 根据 NapCat OpenAPI 4.18.6 生成；请勿手动修改。

package api

// RawMap 表示 OpenAPI 中无法稳定展开的对象字段。
type RawMap = map[string]any
